#!/usr/bin/env bash

kitout_path=/usr/local/opt/kitout

# todo:
# clone/update kitout/core
# clone/update kitout/units-developer
# mkdir /usr/local/opt/kitout/units-local

# Create symlink to dir that is present in OSX's PATH by default
ln -sf $kitout_path/core/kitout /usr/local/bin/kitout
