#!/usr/bin/env bash

kitout_path=/usr/local/opt/kitout

# todo:
# clone/update kitout/core
# clone/update kitout/units-developer
# mkdir /usr/local/opt/kitout/units-local

while read path ; do
  ln -sf $path /usr/local/bin
done < <(ls $kitout_path/core/kitout*)
